apiVersion: 1

contactPoints:
  - orgId: 1
    name: telegram-critical
    receivers:
      - uid: telegram-critical
        type: telegram
        settings:
          bottoken: ${TELEGRAM_BOT_TOKEN}
          chatid: ${TELEGRAM_CHAT_ID}
          parse_mode: HTML
          disable_web_page_preview: true
          protect_content: false
        disableResolveMessage: false

  - orgId: 1
    name: telegram-warnings
    receivers:
      - uid: telegram-warnings
        type: telegram
        settings:
          bottoken: ${TELEGRAM_BOT_TOKEN}
          chatid: ${TELEGRAM_WARNING_CHAT_ID}
          parse_mode: HTML
          disable_web_page_preview: true
        disableResolveMessage: true

notificationPolicies:
  - orgId: 1
    receiver: telegram-critical
    group_by: ['grafana_folder', 'alertname']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: telegram-critical
        object_matchers:
          - ['severity', '=', 'critical']
        group_by: ['alertname', 'service']
        group_wait: 10s
        group_interval: 1m
        repeat_interval: 1h

      - receiver: telegram-warnings
        object_matchers:
          - ['severity', '=', 'warning']
        group_wait: 5m
        group_interval: 10m
        repeat_interval: 4h

      - receiver: telegram-critical
        object_matchers:
          - ['team', '=', 'backend']
          - ['severity', '=', 'critical']
        group_wait: 0s
        group_interval: 30s
        repeat_interval: 30m

messageTemplates:
  - name: telegram.title
    template: |
      {{ if eq .Status "firing" }}🚨 ALERT{{ else }}✅ RESOLVED{{ end }}: {{ .GroupLabels.alertname }}

  - name: telegram.text
    template: |
      {{ if eq .Status "firing" }}
      <b>🔥 Firing Alerts ({{ len .Alerts.Firing }})</b>
      {{ range .Alerts.Firing }}
      
      <b>{{ .Labels.alertname }}</b>
      <i>Severity:</i> {{ .Labels.severity }}
      <i>Service:</i> {{ .Labels.service }}
      <i>Instance:</i> {{ .Labels.instance }}
      
      <b>Summary:</b> {{ .Annotations.summary }}
      <b>Description:</b> {{ .Annotations.description }}
      
      <b>Values:</b>
      {{ range $k, $v := .Values }}
      • {{ $k }}: {{ $v }}
      {{ end }}
      
      <a href="{{ .GeneratorURL }}">📊 View in Grafana</a>
      {{ if .Annotations.runbook_url }}<a href="{{ .Annotations.runbook_url }}">📖 Runbook</a>{{ end }}
      
      <i>Started:</i> {{ .StartsAt.Format "15:04:05 MST" }}
      {{ end }}
      {{ else }}
      <b>✅ All alerts resolved!</b>
      
      {{ range .Alerts.Resolved }}
      • {{ .Labels.alertname }} ({{ .Labels.service }})
      <i>Resolved at:</i> {{ .EndsAt.Format "15:04:05 MST" }}
      {{ end }}
      {{ end }}