version: "3.8"

networks:
  net:
    name: net
    external: true  # Создается в docker-compose.db.yaml

services:
  crmessenger-authorization:
    build:
      context: "../${CRMESSENGER_AUTHORIZATION_NAME}"
      dockerfile: "${CRMESSENGER_MICROSERVICE_DOCKERFILE_DIR}/Dockerfile"
    container_name: "${CRMESSENGER_AUTHORIZATION_NAME}"
    env_file:
      - "./env/.env.app"
      - "./env/.env.db"
      - "./env/.env.monitoring"
    ports:
      - "${CRMESSENGER_AUTHORIZATION_PORT}:${CRMESSENGER_AUTHORIZATION_PORT}"
    restart: unless-stopped
    networks:
      - net

  crmessenger-authentication:
    build:
      context: "../${CRMESSENGER_AUTHENTICATION_NAME}"
      dockerfile: "${CRMESSENGER_MICROSERVICE_DOCKERFILE_DIR}/Dockerfile"
    container_name: "${CRMESSENGER_AUTHENTICATION_NAME}"
    env_file:
      - "./env/.env.app"
      - "./env/.env.db"
      - "./env/.env.monitoring"
    ports:
      - "${CRMESSENGER_AUTHENTICATION_PORT}:${CRMESSENGER_AUTHENTICATION_PORT}"
    restart: unless-stopped
    networks:
      - net

  crmessenger-account:
    build:
      context: "../${CRMESSENGER_ACCOUNT_NAME}"
      dockerfile: "${CRMESSENGER_MICROSERVICE_DOCKERFILE_DIR}/Dockerfile"
    container_name: "${CRMESSENGER_ACCOUNT_NAME}"
    env_file:
      - "./env/.env.app"
      - "./env/.env.db"
      - "./env/.env.monitoring"
    ports:
      - "${CRMESSENGER_ACCOUNT_PORT}:${CRMESSENGER_ACCOUNT_PORT}"
    restart: unless-stopped
    networks:
      - net

  crmessenger-telegram:
    build:
      context: "../${CRMESSENGER_TELEGRAM_NAME}"
      dockerfile: "${CRMESSENGER_MICROSERVICE_DOCKERFILE_DIR}/Dockerfile"
    container_name: "${CRMESSENGER_TELEGRAM_NAME}"
    env_file:
      - "./env/.env.app"
      - "./env/.env.db"
      - "./env/.env.monitoring"
    volumes:
      - "../${CRMESSENGER_TELEGRAM_NAME}/${CRMESSENGER_TELEGRAM_USERBOT_SESSION_DIR}:/root/pkg/session"
    ports:
      - "${CRMESSENGER_TELEGRAM_PORT}:${CRMESSENGER_TELEGRAM_PORT}"
    restart: unless-stopped
    networks:
      - net

  crmessenger-whatsapp:
    build:
      context: "../${CRMESSENGER_WHATSAPP_NAME}"
      dockerfile: "${CRMESSENGER_MICROSERVICE_DOCKERFILE_DIR}/Dockerfile"
    container_name: "${CRMESSENGER_WHATSAPP_NAME}"
    env_file:
      - "./env/.env.app"
      - "./env/.env.db"
      - "./env/.env.monitoring"
    ports:
      - "${CRMESSENGER_WHATSAPP_PORT}:${CRMESSENGER_WHATSAPP_PORT}"
    restart: unless-stopped
    networks:
      - net